List<String> newbooks = [
  'assets/images/1.jpeg',
  'assets/images/2.jpeg',
  'assets/images/3.jpeg',
  'assets/images/4.jpeg',
  // 'assets/images/image1.png',
  // 'assets/images/image2.png',
  // 'assets/images/image3.png',
  // 'assets/images/image4.png',
  // 'assets/images/image5.png',
  // 'assets/images/image6.png',
  // 'assets/images/image1.jpg',
  // 'assets/images/image2.jpg',
  // 'assets/images/image3.jpg',
  // 'assets/images/image4.jpg',
  // 'assets/images/image5.jpg',
  // 'assets/images/image6.jpeg',
];
